name: Call Reusable Build Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml   #Run that entire workflow as a job
    with:
      app_name: "my-web-app"       #we are passing inputs
      environment: "production"
    secrets:
      docker_token: ${{ secrets.DOCKER_TOKEN }}
