name: docker build & push

on:
    push:
        branches: [main]

jobs: 
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v4
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }} #Add both to repo settings under sec # var
                password: ${{ secrets.DOCKERHUB_TOKEN }}     #This we have to create in dockerhub first 

            - name: Build and push Docker image to dockerhub
              uses: docker/build-push-action@v6
              with:
                    context: .    #it should be the root directory of the project where the Dockerfile is located
                    push: true
                    tags: |
                       ${{ vars.DOCKERHUB_USERNAME }}/github-actions-app:${{ github.ref_name }}
                       ${{ vars.DOCKERHUB_USERNAME }}/github-actions-app:latest
                       ${{ vars.DOCKERHUB_USERNAME }}/github-actions-app:${{ github.sha }}  
                      #Simple hashing algorithm to generate unique identifiers for each commit
