name: Ignore Docs Changes

on:
  push:
    branches:
      - main
      - 'release/*'
    paths-ignore:
      - '*.md'
      - 'docs/**'

jobs:
  run-unless-docs-only:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Workflow triggered (not just docs changes)"
