name: Job Outputs Demo

on:
  push:

jobs:
  generate-date:
    runs-on: ubuntu-latest

    outputs:
      today: ${{ steps.get-date.outputs.today }}

    steps:
      - name: Get today's date
        id: get-date
        run: |
          echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

  use-date:
    runs-on: ubuntu-latest
    needs: generate-date

    steps:
      - name: Print date from previous job
        run: |
          echo "Date from previous job: ${{ needs.generate-date.outputs.today }}"
