run-name: PR Event - ${{ github.event.action }}
name: PR Lifecycle

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  pr-info:
    runs-on: ubuntu-latest

    steps:
      - name: Print event type
        run: |
          echo "Event action: ${{ github.event.action }}"

      - name: Print PR title
        run: |
          echo "PR Title: ${{ github.event.pull_request.title }}"

      - name: Print PR author
        run: |
          echo "PR Author: ${{ github.event.pull_request.user.login }}"

      - name: Print source and target branches
        run: |
          echo "Source branch: ${{ github.head_ref }}"
          echo "Target branch: ${{ github.base_ref }}"

      - name: Run only if PR is merged
        if: github.event.action == 'closed' && github.event.pull_request.merged == true   #Run this step ONLY when the PR is closed because it was merged, not just closed manually.
        run: echo "PR was merged"
