name: Reusable Build Workflow

on:
  workflow_call:      #[**Note:** This makes your workflow reusable, meaning: It won’t run on push or PR, It only runs when another workflow calls it]
    inputs:           #You defined parameters that the caller must send like app_name, environment
      app_name:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      docker_token:
        required: true

    outputs:   #MUST be inside workflow_call
      build_version:
        description: "Generated build version"
        value: ${{ jobs.build.outputs.build_version }}

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      build_version: ${{ steps.version.outputs.build_version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print build info                #This is how you access inputs inside steps
        run: echo "Building ${{ inputs.app_name }} for ${{ inputs.environment }}"

      - name: Verify secret is set
        run: echo "Docker token is set: true"

      - name: Generate version
        id: version
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)           #GITHUB_SHA → full commit hash, cut -c1-7 → short SHA
          VERSION="v1.0-$SHORT_SHA"
          echo "build_version=$VERSION" >> $GITHUB_OUTPUT     #$GITHUB_OUTPUT → official way to pass step outputs
